name: Deploy to DigitalOcean

on:
  push:
    branches:
      - lito_dev  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
        DO_HOST: ${{ secrets.DO_HOST }}
        DO_USERNAME: ${{ secrets.DO_USERNAME }}
      run: |
        echo "$DO_SSH_KEY" > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -r . $DO_USERNAME@$DO_HOST:/root/facilicty-management/facility-management-backend
        ssh -i deploy_key $DO_USERNAME@$DO_HOST "cd /root/facilicty-management/facility-management-backend && docker-compose up --build -d"
        rm -f deploy_key
